FROM centos
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
RUN yum install httpd -y
# Copia run sh dentro del container en la ubicación /run.sh
COPY run.sh /run.sh
# Ejecuta run.sh
CMD sh /run.sh